### ISSUE TITLE
mac casks and linux binary through package managers

### ISSUE THREAD

**Issue by mTvare6** [DevbookHQ/devbook-extension#2]
A homebrew cask and debian based binary for package mangers will make it easier to install.

PS: add issue templates

**Comment by mlejva** [comment]
Thank you for the feedback.

This repo is intended only for Devbook extensions. If I understand your suggestion correctly it's about the distribution of the Devbook app itself, right?

If that's the case, please feel free to reach out to vasek\<at\>usedevbook.com with any app-level feedback. Or join our [Discord community](https://discord.gg/ZkmbtJhY9g)!

Let's leave this only for extension issues.

Thank you!
